// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmnSrHqWfEscHK_aHRf9RQ2b_IX-S4F6I',
    appId: '1:16230407684:web:3f6b83955c8483fe69df51',
    messagingSenderId: '16230407684',
    projectId: 'weather-app-flutter-monstarlab',
    authDomain: 'weather-app-flutter-monstarlab.firebaseapp.com',
    storageBucket: 'weather-app-flutter-monstarlab.appspot.com',
    measurementId: 'G-6FZSC7XC8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfnXEdbuh2LGMeUfxkQWZro0UjxL3Lu2M',
    appId: '1:16230407684:android:73103dbed77c403169df51',
    messagingSenderId: '16230407684',
    projectId: 'weather-app-flutter-monstarlab',
    storageBucket: 'weather-app-flutter-monstarlab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBNkpgKxK-JwQWQpdpgahGulAL3wdK5Wc',
    appId: '1:16230407684:ios:27e57382d467238369df51',
    messagingSenderId: '16230407684',
    projectId: 'weather-app-flutter-monstarlab',
    storageBucket: 'weather-app-flutter-monstarlab.appspot.com',
    iosClientId: '16230407684-uob8v509qtum9cr9j4uhvtumhgaag7sm.apps.googleusercontent.com',
    iosBundleId: 'com.tansangle.weatherAppFlutterMonstarlab',
  );
}
